### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [mode-js/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, end result looks good. You used some good techniques here. I appreciate that you wanted to really customize the look of the project. Than being said it is important to learn how to make your code efficient and reusable. You want to design your html and css as components that can be reused and plugged in where they are needed. Take a look at the issues I created as they will point out some places this can be improved. 
https://www.codecademy.com/articles/classes-vs-ids

**Comment by mode-js** [comment]
Awesome! thank you for your honest critiques.  I know that this is going to take several months (*or years*) to really because a good web developer and I have already been working with a few developers that have been working with me to give me pointers.  But i know that having this crouse is going to help me so much. 

I have a few websites that are built using SCSS (or SASS) which I find a lot easier to use than CSS because it builds my main.css file for me. 

But i want to be more proficient and comfortable using the CSS styles to help me build these websites. 

I am making a few final changes to remove the redundant code/styles from the CSS and then I will push it back to the repo.

**Comment by mode-js** [comment]
Here is my latest project if you have time to take a look at it: https://mode-js.github.io/broadway

**Comment by mode-js** [comment]
Or the actual files can be found here: https://github.com/mode-js/broadway.  Thanks @rimmesbe

**Comment by mode-js** [comment]
Hello @rimmesbe -- I have a few questions and never heard back from you on a few things.  Just finished the My Times project and here is the new link: 

https://mode-js.github.io/mytimes/

Would love to hear any feedback you my have. 

Thank you!
Adam
